name: Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: ${{ matrix.ruby != '2.5' }} # https://github.com/sider/goodcheck/pull/195/checks?check_run_id=2735777166#step:3:70
      - run: gem update --system && bundle install
        if: ${{ matrix.ruby == '2.5' }}
      - run: bundle exec rake
        env:
          TESTOPT: "--verbose"
          COVERAGE: ${{ matrix.ruby == '3.0' }}
      - uses: actions/upload-artifact@v3
        if: ${{ hashFiles('coverage/index.html') != '' }}
        with:
          name: coverage
          path: coverage/
          retention-days: 7
